### ISSUE TITLE
Discussion Thread for CBP-Theme-Roadmap

### ISSUE THREAD

**Issue by yogeshgadge** [US-CBP/cbp-theme#172]
:bulb: Opening this discussion thread for [CBP Theme Roadmap](https://github.com/US-CBP/cbp-theme/wiki/CBP-Theme-Roadmap) created by @davezen1

**Comment by yogeshgadge** [comment]
Here are my thoughts:-

> Should we support only Material Design going forward? If so, which implementation?

* I like [Material Design specs](https://material.io/) which has been well thought out specifications. 
* Implementation:-
** There is only one universal Material Design spec hence the motivation for implementation is the ease of use in your app and how well the library is written.
** Then shouldn't the implementation be choose from one of the 2 big libraries React or Angular ? 


> Should we support Bootstrap 3, 4?

* If bootstrap then Bootstrap 4 however I would juts go with Material Design. 

> What would make the CBP Theme easier to use with frameworks like Angular and React?

* If cbp-theme itself or its KitchenSink is implemented in one of the 2 implementations (Angular or React) it would make it  easier for both camps - one more than other. It benefits other camp also since there are so many parallels in the component architectures of React and Angular.
* This picking of one component framework will encourage modularization of the SCSS files.

**Comment by jscharett** [comment]
@yogeshgadge  I have to disagree.

The main issue with Material Design[MD] is simply that it is a spec.  There is nothing conforming you on how to implement the spec.  Hence there are numerous versions of MD ([material-components](https://github.com/material-components/material-components-web/), [material-design-lite](https://github.com/google/material-design-lite), [material2](https://github.com/angular/material2), [material-ui](https://github.com/callemall/material-ui)).  While each implementation conforms to the spec, each use there own styles/markup to do.  MD is not a framework, so it does not specify any constraints there.  So there is no universal "theme" styles that CBP-theme can create that will support everyone.

Conversely, Bootstrap[BS] is framework that specifies how to markup your page so that it will work with the Bootstrap CSS.  Any library supporting BS, must conform to that to be compliant.  So libraries like [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) and [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) simply need to build their components to comply with the BS framework.  They don't really supply much if any styling at that comes from the BS theme.  By using BS, teams can pick their component library and CBP-theme can provide the styles.  The theme should be re-usable across any BS app.  The theme can be 'framework' agnostic in the sense that it supports BS.

I agree that we should support BS v4 over v3.  Much work has been done on v4 to ease the implementation for other frameworks like React/Angular.  It also embraces flex where as v3 relies heavily on floats, which are cumbersome and problematic.

Also, by supporting a framework like BS, the need to access the SCSS files can be reduced and possibly eliminated.  No need to access the SCSS variables to create classes to support your implementation, as your implementation would simply comply to BS.  Projects like [ngx-cbp-theme](https://github.com/US-CBP/ngx-cbp-theme) would no longer need to worry about creates a theme for Angular, rather they would become component libraries.  It would greatly simplify those projects and allow them to decouple from the CBP-theme;  they only need to conform to BS, nothing more.

Granted, its not as simple as I make it sound, but trying to support a spec like MD is much more difficult than a framework like BS.

**Comment by jscharett** [comment]
I also find the Material Design Forms a bit problematic.  They seem to add flare to things at the sacrifice of usability/accessibility.  For example, having a textfield with a transparent background and no borders does not immediately appear as a textfield.  I look at many of these examples and they don't appear as forms to me.  Trying to alter the styling to fix the problem not only diverts from the Style Guide, but is painful, based on the implementation of Material Design.  I know of teams that simply are choosing not to use the MD forms for this reason, which seems to diverge from the end goal here of having apps look/feel be consistent.

**Comment by yogeshgadge** [comment]
I am thinking that we need to distinguish between the following terms as we (I myself sometimes ) use these loosely and to promote objective discussion. 
It is important to understand in the context of
 > What would make the CBP Theme easier to use with frameworks like Angular and React?

Please pitch in if any important point is missing. Again these are what I believe to be the established definitions. So here it goes..

### Specs
Guidelines, Specs e.g. [https://material.io/**guidelines**/](https://material.io/guidelines/). We should not be expecting CSS or look for markup Guidelines here or compare with Bootstrap.   

### Framework Agnostic - UI Library
Key things to note:
- Provides consumable one of many forms of CSS.
  - Some libraries provide a single namespace. e.g. mdl- , mdc-, mat-
- Specific implementation They provide JavaScript for complex behavior where CSS falls short. 
  - Unfortunately it has to also provide JavaScript (cause CSS falls short in the area of Behavior/Feel).
  - As soon as this JS code starts maintaining component states and making DOM manipulation

e.g.
Twitter's Bootstrap, Google's Material Design Components (Material Design Lite), Materialize.

### Application Framework

Provides structure that help your application with the following:-
* Organizing artifacts & separation of concerns for application maintainability. 
* Provides constructs for efficient runtime with optimal resources - Memory, CPU/GPU thus allowing for high performance, offline and whole sleuth of other capabilities like SPA.

### Framework Driven - UI Libraries

Surprisingly there is quite a gap that needs to be bridged between the JS exposed in the **Framework Agnostic UI Libraries** and your Model i.e. You want this model to be available in your Framework API. 

Hence React and Angular are not using the **Framework Agnostic - UI Library** directly because their JS ceased to be agnostic (probably due to use of DOM access via jQuery or some ways that broke the framework's principle).

**Comment by yogeshgadge** [comment]
@jscharett Clarifications: I think you are thinking that I am suggesting that we implement the Material Design specs ourselves. Material Design (specs) cannot be compared with Bootstrap.  We can compare Bootstrap to Material Design Components (MDC), Materialize, etc. Earlier I suggested that we pick `@angular/material2` for Angular or the `material-ui` for React for ease implying we go for a concrete implementation.

However I heard that timeline wise CBP Theme 2.0 is a much farther than what I thought so based on that I am thinking  [**Material Design Components - MDC-web**](https://material.io/components/) would be a good replacement for Material Design (implementation). There is a possibility that `@angular/material2` will go to `mdc` as per this [comment by jelbourn](https://github.com/angular/material2/issues/4154#issuecomment-295508021)

My reasons:-

- MDC-Web claim keeping this UI Library to be framework independent. 
(Although only time and some experimenting will tell since their basic examples are very "basic".). 
- Official Material Design implementation. (Google and under material.io/components)
- [MDC author commenting on React Material UI](https://github.com/callemall/material-ui/issues/6799#issuecomment-299925174}
- There is also a Preact framework for the React folks.
 
Bootstrap 4 cannot be consumed to the fullest directly in Angular applications in React (which explains why there is ngx-bootstrap and react-bootstrap) - as one can only consume the CSS framework parts of it. The moment we try to provide the JS we will get into a business of creating components aka Framework Dependent UI Library providers.

**Comment by jscharett** [comment]
@yogeshgadge 

> Bootstrap 4 cannot be consumed to the fullest directly in Angular applications in React

With regards to consuming Bootstrap in React/Angular, you would use the corresponding library [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap)/[ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) that works with framework.  No need to use the Bootstrap js at all.

Another issue I'm having with Angular Material, is that they currently implement their own CSS.  This makes overriding their styles difficult as their CSS loads on demand per component.  This is nice if you want to use Material as-is, but as soon as you want to change something like padding, its problematic.  When/if they change to MDC, that issue may go away, but it appears to be low-priority.  And it would seemingly only solve the Angular side, as it appears the React folks have chosen not to impl MDC for the time being.

**Comment by r1teshkumar** [comment]
Closing thread, since it is not active any more. Discussion points will be taken into account for future Major release of CBP theme.
