### ISSUE TITLE
App header and cbp-header z-index values are backwards, causing navbar dropdowns to hide behind the app-header

### ISSUE THREAD

**Issue by djKianoosh** [US-CBP/cbp-theme#269]
In CBP Theme 1.10.2, we notice that the `.app-header` `z-index` is 9. When scrolling, `.app-header.top`'s `z-index` is 11.  The problem comes when we have a fixed global header, because `cbp-header`'s `z-index` is 10. Making `cbp-header`'s `z-index` 12 appears to fix this issue without causing modals and other widgets to hide behind the header. The example given in #240 makes things worse.

**Comment by HIGGO36** [comment]
Upon initial inspection, looks like the z-indexes for the classes mentioned above have been updated to:
.app-header z-index is 1000
.cbp-header z-index is 1010
.app-header.top z-index is 1030

( Not sure if there is still an issue with this? )
-------------------------------------------------------------------------------------------------------------------
Also, while looking into this issue I noticed a difference  between the App Directory and the CBP Theme's
<div class="app-header" role="navigation">, where the "top" class is not being dynamically applied as it is within the app directory index.

I'm guessing this was intentional, however looks like the script controlling this at, 
( https://apps-dev.sat.cbp.dhs.gov/ta/landing/dist/cbp-theme.min.js ) is not being referenced on the CBP Theme index.
